//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1714dswartoutex2h
{
    using System;
    using System.Collections.Generic;
    
    public partial class Run
    {
        public int Id { get; set; }
        public System.DateTime DateSubmitted { get; set; }
        public System.TimeSpan TimeElapsed { get; set; }
    
        public virtual Person Player { get; set; }
        public virtual Game Game { get; set; }
    }
}
